### ISSUE TITLE
[Web] Remove '[...]' from query parameters

### ISSUE THREAD

**Issue by askrid** [swsnu/swppfall2022-team17#58]
Prevent  '[' and ']' characters to be included in the query parameters, e.g. when using 'redirect' parameter. This causes runtime errors.

**Comment by ozeeeno** [comment]
is this just for notice?

**Comment by askrid** [comment]
> is this just for notice?

https://github.com/swsnu/swppfall2022-team17/pull/61에 연결되었습니다.
